name: Clang Format Checker
on:
  push:
    branches : [ "main" ]
  pull_request:
    branches : [ "main" ]

jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run clang-format
        uses: RafikFarhad/clang-format-github-action@v6
        with:
          sources: "src/*.c, src/*.h, tests/*.c"
          style: file
